# Generated by Django 5.2.8 on 2025-11-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='migrated@example.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
