# Generated by Django 5.2.8 on 2025-12-01 01:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_articlecategory_cvtemplate_knowledgecategory_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('primary_skills', models.TextField(blank=True, null=True)),
                ('work_preferences', models.CharField(blank=True, max_length=100, null=True)),
                ('suggested_path', models.CharField(blank=True, max_length=50, null=True)),
                ('service_branch', models.CharField(blank=True, max_length=200, null=True)),
                ('service_role', models.CharField(blank=True, max_length=300, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_service', models.IntegerField(blank=True, null=True)),
                ('discharge_date', models.CharField(blank=True, max_length=50, null=True)),
                ('deployment_experience', models.BooleanField(default=False)),
                ('leadership_experience', models.BooleanField(default=False)),
                ('civilian_certifications', models.TextField(blank=True, null=True)),
                ('disabilities_or_limits', models.TextField(blank=True, null=True)),
                ('security_clearance', models.CharField(blank=True, max_length=50, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('benefits_awareness', models.CharField(blank=True, max_length=50, null=True)),
                ('support_needs', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_assessments',
            },
        ),
    ]
