# Generated by Django 5.2.8 on 2025-12-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conv_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
