# Generated by Django 5.2.8 on 2025-12-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_conv_type_to_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conv_type',
            field=models.CharField(blank=True, choices=[('Business', 'Власний бізнес'), ('SelfEmployment', 'Самозайнятість'), ('Hiring', 'Наймана праця'), ('CareerPath', 'Вибір напрямку'), ('Education', 'Навчання')], default='', max_length=50),
        ),
    ]
