# Generated by Django 5.2.8 on 2025-12-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_conversation_conv_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='final_verdict',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='financial_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='market_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='risk_assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='skills_match',
            field=models.TextField(blank=True, default=''),
        ),
    ]
