# Generated by Django 5.2.8 on 2025-12-02 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_article_tags_and_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conv_type',
            field=models.CharField(blank=True, choices=[('BUSINESS', 'Власний бізнес'), ('SELF_EMPLOYMENT', 'Самозайнятість'), ('HIRING', 'Наймана праця'), ('CAREER_PATH', 'Вибір напрямку'), ('EDUCATION', 'Навчання')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
