# Generated by assistant: remove CVTemplate model and Resume.template field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_cvtemplate_name_alter_cvtemplate_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='template',
        ),
        migrations.DeleteModel(
            name='cvtemplate',
        ),
    ]
