# Generated by Django 5.2.9 on 2025-12-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_resume_template_id_and_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='preferred_language',
            field=models.CharField(blank=True, default='uk', max_length=50, null=True),
        ),
    ]
