# Generated by Django 5.2.9 on 2025-12-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userassessment_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassessment',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('uk', 'Українська'), ('en', 'English'), ('ru', 'Русский')], default='uk', max_length=10),
        ),
    ]
