# Generated by Django 5.2.8 on 2025-11-26 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('step_order', models.IntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('BRAINSTORM', 'Brainstorm'), ('RESEARCH', 'Research'), ('VALIDATION', 'Validation')], default='BRAINSTORM', max_length=20)),
                ('validation_score', models.IntegerField(default=0)),
                ('business_canvas', models.JSONField(blank=True, default=dict)),
                ('market_research', models.JSONField(blank=True, default=dict)),
                ('summary_card_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
