# Generated by Django 5.2.8 on 2025-11-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionstep',
            name='business_idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_steps', to='ideas.businessidea'),
        ),
    ]
